image: node:11

cache:
  paths:
    - node_modules/

stages:
  - build
  - ship

compile:
  stage: build
  script:
    - yarn reset
    - yarn build:production
  artifacts:
    paths:
      - dist

pages:
  stage: ship
  script:
    - mv dist public
  artifacts:
    paths:
      - public
